channels:
  - name: "テレ東BIZ ダイジェスト"
    channel_id: "UCkKVQ_GNjd8FbAuT6xDcWgg"
  - name: "日経CNBC"
    channel_id: "UClVsQnfs-jKkjKmUKUHnT2g"
    title_filter: "東京株式市場"
  - name: "トウシル(楽天証券)"
    channel_id: "UC5BiTvy2Ni2MyigJPspjhOA"
